// <auto-generated />
using System;
using EcoTokenSystem.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcoTokenSystem.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251224095915_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EcoTokenSystem.Domain.Entities.Items", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequiredPoints")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e2b1a8c0-4e3d-4b7f-8c9a-6f2e0d1b4c5a"),
                            ImageUrl = "/imagesItem/4cf97def-f0ef-4a06-899d-dbffa4e2f02f.jpg",
                            Name = "Túi xách vải ",
                            RequiredPoints = 500
                        },
                        new
                        {
                            Id = new Guid("d7a5f4b3-2c1e-4a9d-9b8c-3f0a7e6d5b4c"),
                            ImageUrl = "/imagesItem/af1c1380-7edc-40cf-afd1-95b6f8b6d91e.jpg",
                            Name = "Bình nước Thân thiện Môi trường",
                            RequiredPoints = 1000
                        },
                        new
                        {
                            Id = new Guid("c1e9d8a7-b6f5-4e3d-2c1b-0a9f8e7d6c5b"),
                            ImageUrl = "/imagesItem/6144411c-172b-45d0-abcb-ae714ea825a5.jpg",
                            Name = "Ống hút Tre",
                            RequiredPoints = 400
                        },
                        new
                        {
                            Id = new Guid("ebb8e449-506c-4f12-9bac-15a63edd502f"),
                            ImageUrl = "/imagesItem/75e0829b-fb8f-47f1-9977-d0d377aaca9d.jpg",
                            Name = "Set quà tặng bằng tre ",
                            RequiredPoints = 150
                        },
                        new
                        {
                            Id = new Guid("ed322a69-55b6-47c6-909d-2ce26aaf5a11"),
                            ImageUrl = "/imagesItem/8e5f5ba6-8d81-4333-842d-292399c4a44c.jpg",
                            Name = "Hộp bút thân thiện với môi trường",
                            RequiredPoints = 200
                        },
                        new
                        {
                            Id = new Guid("046564c4-882e-49c7-bd74-eb38d41ef521"),
                            ImageUrl = "/imagesItem/76b61892-6589-4fd1-af0c-9f02311683c9.jpg",
                            Name = "Giá đỡ máy tính bảng bằng tre",
                            RequiredPoints = 100
                        });
                });

            modelBuilder.Entity("EcoTokenSystem.Domain.Entities.ItemsHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("RedemptionDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("UserId");

                    b.ToTable("ItemsHistory");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c9d8e7f6-a5b4-3c2d-1e0f-9876543210ab"),
                            ItemId = new Guid("c1e9d8a7-b6f5-4e3d-2c1b-0a9f8e7d6c5b"),
                            RedemptionDate = new DateTime(2025, 12, 21, 9, 59, 11, 742, DateTimeKind.Utc).AddTicks(686),
                            UserId = new Guid("a3c72b9a-5d2e-4f8a-9a1c-4e1d8a2c9b6a")
                        });
                });

            modelBuilder.Entity("EcoTokenSystem.Domain.Entities.PointHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AdminId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PointsChange")
                        .HasColumnType("int");

                    b.Property<Guid?>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("PointHistories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1a2c3d4-e5f6-7890-abcd-ef0123456789"),
                            AdminId = new Guid("f3e09f3d-6a2a-47c1-80f1-622abce815ca"),
                            PointsChange = 600,
                            PostId = new Guid("1a2b3c4d-5e6f-7a8b-9c0d-1e2f3a4b5c6d"),
                            TransactionDate = new DateTime(2025, 12, 15, 9, 59, 11, 742, DateTimeKind.Utc).AddTicks(616),
                            UserId = new Guid("a3c72b9a-5d2e-4f8a-9a1c-4e1d8a2c9b6a")
                        },
                        new
                        {
                            Id = new Guid("ca2d49d6-7f95-4e49-a5ca-03c199ad70e7"),
                            AdminId = new Guid("f3e09f3d-6a2a-47c1-80f1-622abce815ca"),
                            PointsChange = 900,
                            TransactionDate = new DateTime(2025, 12, 14, 8, 59, 11, 742, DateTimeKind.Utc).AddTicks(662),
                            UserId = new Guid("a3c72b9a-5d2e-4f8a-9a1c-4e1d8a2c9b6a")
                        });
                });

            modelBuilder.Entity("EcoTokenSystem.Domain.Entities.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AdminId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ApprovedRejectedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("AwardedPoints")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("StatusId");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1a2b3c4d-5e6f-7a8b-9c0d-1e2f3a4b5c6d"),
                            AdminId = new Guid("f3e09f3d-6a2a-47c1-80f1-622abce815ca"),
                            ApprovedRejectedAt = new DateTime(2025, 12, 15, 9, 59, 11, 742, DateTimeKind.Utc).AddTicks(587),
                            AwardedPoints = 600,
                            Content = "Đây là bài viết mẫu đã được duyệt.",
                            ImageUrl = "/images/seed/post1.jpg",
                            StatusId = 2,
                            SubmittedAt = new DateTime(2025, 12, 14, 9, 59, 11, 742, DateTimeKind.Utc).AddTicks(581),
                            Title = "Cách phân loại rác hiệu quả",
                            UserId = new Guid("a3c72b9a-5d2e-4f8a-9a1c-4e1d8a2c9b6a")
                        },
                        new
                        {
                            Id = new Guid("f5e4d3c2-b1a0-9876-5432-10fedcba9876"),
                            AwardedPoints = 0,
                            Content = "Bài viết mẫu đang chờ duyệt  .",
                            ImageUrl = "/images/seed/post2.jpg",
                            StatusId = 1,
                            SubmittedAt = new DateTime(2025, 12, 19, 9, 59, 11, 742, DateTimeKind.Utc).AddTicks(593),
                            Title = "Tại sao cần dùng túi tái chế?  ",
                            UserId = new Guid("a3c72b9a-5d2e-4f8a-9a1c-4e1d8a2c9b6a")
                        });
                });

            modelBuilder.Entity("EcoTokenSystem.Domain.Entities.PostStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PostStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pending"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Approved"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Rejected"
                        });
                });

            modelBuilder.Entity("EcoTokenSystem.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "User"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("EcoTokenSystem.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentPoints")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("Streak")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f3e09f3d-6a2a-47c1-80f1-622abce815ca"),
                            Address = "",
                            CreatedAt = new DateTime(2025, 12, 24, 9, 59, 11, 742, DateTimeKind.Utc).AddTicks(513),
                            CurrentPoints = 99999,
                            Gender = "",
                            Name = "Quản trị viên Hệ thống",
                            PasswordHash = "$2a$11$U7Uui5d.WbC1UDdblLBNquo5Q3y9EXd81VUkYwXMoqU3fpViUFMs2",
                            PhoneNumber = "",
                            RoleId = 2,
                            Streak = 99999,
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("a3c72b9a-5d2e-4f8a-9a1c-4e1d8a2c9b6a"),
                            Address = "",
                            CreatedAt = new DateTime(2025, 12, 24, 9, 59, 11, 742, DateTimeKind.Utc).AddTicks(516),
                            CurrentPoints = 1500,
                            Gender = "",
                            Name = "Nhật Anh",
                            PasswordHash = "$2a$11$kiLYvtupDCK9GP.euIwgHuo7y6Ko66w9GAL2bRQJzoDo9/Bhm5ZwG",
                            PhoneNumber = "",
                            RoleId = 1,
                            Streak = 0,
                            Username = "user_test"
                        });
                });

            modelBuilder.Entity("EcoTokenSystem.Domain.Entities.ItemsHistory", b =>
                {
                    b.HasOne("EcoTokenSystem.Domain.Entities.Items", "Item")
                        .WithMany("RedemptionHistory")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EcoTokenSystem.Domain.Entities.User", "User")
                        .WithMany("ItemsHistory")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EcoTokenSystem.Domain.Entities.PointHistory", b =>
                {
                    b.HasOne("EcoTokenSystem.Domain.Entities.User", "Admin")
                        .WithMany("TransactionsMade")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EcoTokenSystem.Domain.Entities.Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostId");

                    b.HasOne("EcoTokenSystem.Domain.Entities.User", "User")
                        .WithMany("PointsHistory")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EcoTokenSystem.Domain.Entities.Post", b =>
                {
                    b.HasOne("EcoTokenSystem.Domain.Entities.User", "Admin")
                        .WithMany("PostsApproved")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EcoTokenSystem.Domain.Entities.PostStatus", "Status")
                        .WithMany("Posts")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcoTokenSystem.Domain.Entities.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Status");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EcoTokenSystem.Domain.Entities.User", b =>
                {
                    b.HasOne("EcoTokenSystem.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("EcoTokenSystem.Domain.Entities.Items", b =>
                {
                    b.Navigation("RedemptionHistory");
                });

            modelBuilder.Entity("EcoTokenSystem.Domain.Entities.PostStatus", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("EcoTokenSystem.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("EcoTokenSystem.Domain.Entities.User", b =>
                {
                    b.Navigation("ItemsHistory");

                    b.Navigation("PointsHistory");

                    b.Navigation("Posts");

                    b.Navigation("PostsApproved");

                    b.Navigation("TransactionsMade");
                });
#pragma warning restore 612, 618
        }
    }
}
