// <auto-generated />
using System;
using EcoTokenSystem.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcoTokenSystem.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251123062040_FullDatabaseSetupV2")]
    partial class FullDatabaseSetupV2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EcoTokenSystem.Domain.Entities.Items", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequiredPoints")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e2b1a8c0-4e3d-4b7f-8c9a-6f2e0d1b4c5a"),
                            ImageUrl = "/images/rewards/voucher50k.png",
                            Name = "Voucher Cây Xanh 50k",
                            RequiredPoints = 500
                        },
                        new
                        {
                            Id = new Guid("d7a5f4b3-2c1e-4a9d-9b8c-3f0a7e6d5b4c"),
                            ImageUrl = "/images/rewards/reusablebottle.png",
                            Name = "Bình nước Thân thiện Môi trường",
                            RequiredPoints = 1000
                        },
                        new
                        {
                            Id = new Guid("c1e9d8a7-b6f5-4e3d-2c1b-0a9f8e7d6c5b"),
                            ImageUrl = "/images/rewards/bamboo_straws.png",
                            Name = "Ống hút Inox/Tre",
                            RequiredPoints = 400
                        });
                });

            modelBuilder.Entity("EcoTokenSystem.Domain.Entities.ItemsHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("RedemptionDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("UserId");

                    b.ToTable("ItemsHistory");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c9d8e7f6-a5b4-3c2d-1e0f-9876543210ab"),
                            ItemId = new Guid("c1e9d8a7-b6f5-4e3d-2c1b-0a9f8e7d6c5b"),
                            RedemptionDate = new DateTime(2025, 11, 20, 6, 20, 38, 656, DateTimeKind.Utc).AddTicks(6506),
                            UserId = new Guid("a3c72b9a-5d2e-4f8a-9a1c-4e1d8a2c9b6a")
                        });
                });

            modelBuilder.Entity("EcoTokenSystem.Domain.Entities.PointHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AdminId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PointsChange")
                        .HasColumnType("int");

                    b.Property<Guid?>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("PointHistories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1a2c3d4-e5f6-7890-abcd-ef0123456789"),
                            AdminId = new Guid("f3e09f3d-6a2a-47c1-80f1-622abce815ca"),
                            PointsChange = 600,
                            PostId = new Guid("1a2b3c4d-5e6f-7a8b-9c0d-1e2f3a4b5c6d"),
                            TransactionDate = new DateTime(2025, 11, 14, 6, 20, 38, 656, DateTimeKind.Utc).AddTicks(6447),
                            UserId = new Guid("a3c72b9a-5d2e-4f8a-9a1c-4e1d8a2c9b6a")
                        },
                        new
                        {
                            Id = new Guid("b877f78e-10c2-4934-91b0-14df2e884878"),
                            AdminId = new Guid("f3e09f3d-6a2a-47c1-80f1-622abce815ca"),
                            PointsChange = 900,
                            TransactionDate = new DateTime(2025, 11, 13, 5, 20, 38, 656, DateTimeKind.Utc).AddTicks(6487),
                            UserId = new Guid("a3c72b9a-5d2e-4f8a-9a1c-4e1d8a2c9b6a")
                        });
                });

            modelBuilder.Entity("EcoTokenSystem.Domain.Entities.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AdminId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ApprovedRejectedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("AwardedPoints")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("StatusId");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1a2b3c4d-5e6f-7a8b-9c0d-1e2f3a4b5c6d"),
                            AdminId = new Guid("f3e09f3d-6a2a-47c1-80f1-622abce815ca"),
                            ApprovedRejectedAt = new DateTime(2025, 11, 14, 6, 20, 38, 656, DateTimeKind.Utc).AddTicks(6419),
                            AwardedPoints = 600,
                            Content = "Đây là bài viết mẫu đã được duyệt.",
                            ImageUrl = "/images/seed/post1.jpg",
                            StatusId = 2,
                            SubmittedAt = new DateTime(2025, 11, 13, 6, 20, 38, 656, DateTimeKind.Utc).AddTicks(6413),
                            Title = "Cách phân loại rác hiệu quả",
                            UserId = new Guid("a3c72b9a-5d2e-4f8a-9a1c-4e1d8a2c9b6a")
                        },
                        new
                        {
                            Id = new Guid("f5e4d3c2-b1a0-9876-5432-10fedcba9876"),
                            AwardedPoints = 0,
                            Content = "Bài viết mẫu đang chờ duyệt  .",
                            ImageUrl = "/images/seed/post2.jpg",
                            StatusId = 1,
                            SubmittedAt = new DateTime(2025, 11, 18, 6, 20, 38, 656, DateTimeKind.Utc).AddTicks(6424),
                            Title = "Tại sao cần dùng túi tái chế?  ",
                            UserId = new Guid("a3c72b9a-5d2e-4f8a-9a1c-4e1d8a2c9b6a")
                        });
                });

            modelBuilder.Entity("EcoTokenSystem.Domain.Entities.PostStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PostStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pending"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Approved"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Rejected"
                        });
                });

            modelBuilder.Entity("EcoTokenSystem.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "User"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("EcoTokenSystem.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentPoints")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("Streak")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f3e09f3d-6a2a-47c1-80f1-622abce815ca"),
                            Address = "",
                            CreatedAt = new DateTime(2025, 11, 23, 6, 20, 38, 656, DateTimeKind.Utc).AddTicks(6353),
                            CurrentPoints = 99999,
                            Gender = "",
                            Name = "Quản trị viên Hệ thống",
                            PasswordHash = "$2a$11$EhuJDVclmnf9qxTKPHeFHer5/OU.1qNQY5ruQLw5H41qcxZGdgFVa",
                            PhoneNumber = "",
                            RoleId = 2,
                            Streak = 99999,
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("a3c72b9a-5d2e-4f8a-9a1c-4e1d8a2c9b6a"),
                            Address = "",
                            CreatedAt = new DateTime(2025, 11, 23, 6, 20, 38, 656, DateTimeKind.Utc).AddTicks(6356),
                            CurrentPoints = 1500,
                            Gender = "",
                            Name = "Nhật Anh",
                            PasswordHash = "$2a$11$20oqzcA./Vi/73cq2lufm.mED1zhLTRSceStGySIifhHrk7WqHHZ.",
                            PhoneNumber = "",
                            RoleId = 1,
                            Streak = 0,
                            Username = "user_test"
                        });
                });

            modelBuilder.Entity("EcoTokenSystem.Domain.Entities.ItemsHistory", b =>
                {
                    b.HasOne("EcoTokenSystem.Domain.Entities.Items", "Item")
                        .WithMany("RedemptionHistory")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EcoTokenSystem.Domain.Entities.User", "User")
                        .WithMany("ItemsHistory")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EcoTokenSystem.Domain.Entities.PointHistory", b =>
                {
                    b.HasOne("EcoTokenSystem.Domain.Entities.User", "Admin")
                        .WithMany("TransactionsMade")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EcoTokenSystem.Domain.Entities.Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostId");

                    b.HasOne("EcoTokenSystem.Domain.Entities.User", "User")
                        .WithMany("PointsHistory")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EcoTokenSystem.Domain.Entities.Post", b =>
                {
                    b.HasOne("EcoTokenSystem.Domain.Entities.User", "Admin")
                        .WithMany("PostsApproved")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EcoTokenSystem.Domain.Entities.PostStatus", "Status")
                        .WithMany("Posts")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcoTokenSystem.Domain.Entities.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Status");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EcoTokenSystem.Domain.Entities.User", b =>
                {
                    b.HasOne("EcoTokenSystem.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("EcoTokenSystem.Domain.Entities.Items", b =>
                {
                    b.Navigation("RedemptionHistory");
                });

            modelBuilder.Entity("EcoTokenSystem.Domain.Entities.PostStatus", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("EcoTokenSystem.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("EcoTokenSystem.Domain.Entities.User", b =>
                {
                    b.Navigation("ItemsHistory");

                    b.Navigation("PointsHistory");

                    b.Navigation("Posts");

                    b.Navigation("PostsApproved");

                    b.Navigation("TransactionsMade");
                });
#pragma warning restore 612, 618
        }
    }
}
